### ISSUE TITLE
Atlassian integration broken

### ISSUE THREAD

**Issue by rmausz82** [clockify/browser-extension#108]
In jira cloud there is no link to start timer any more in the ticket view.

JS-Console shows error:
VM179 atlassian.js:85 Uncaught TypeError: Cannot read property '1' of null
    at VM179 atlassian.js:85
    at Object.renderTo (VM178 button.js:26)
    at MutationObserver.<anonymous> (VM178 button.js:16)

**Comment by rmausz82** [comment]
additional js error
Error handling response: TypeError: Cannot read property 'length' of undefined
at updateButtonState (chrome-extension://pmjeegjhjdlccodhacdgbgfagbpmccpe/integrations/button.js:227:54)
at chrome-extension://pmjeegjhjdlccodhacdgbgfagbpmccpe/integrations/button.js:297:18

**Comment by aleksandar-olic** [comment]
We no longer officially maintain the Jira integration via the extension (the layout in Jira keeps changing constantly).

We recommend either: 

- Integrating via the Atlassian store: https://marketplace.atlassian.com/apps/1222624/clockify-time-tracking-timesheet 
- Or wait until someone from the community fixes the extension's integration

**Comment by rmausz82** [comment]
in Line #36  remove .css-vfoyut from the selector.
https://github.com/clockify/browser-extension/blob/0c3a8f01d7b0bcb1bac116862cd86247e5ccc6b9/src/integrations/atlassian.js#L36

With this change it works for Modal screens in kanban boards. On the first time it won't, problable due to some other js-error in the "One issue fullscreen" section. After that it works fine.

**Comment by dorfman2** [comment]
This issue has definitely affected my workflow. Just giving it a bump by saying it effects me also.

**Comment by rmausz82** [comment]
@dorfman2 your problem is probably some javascript error like this

Uncaught TypeError: Cannot read property '1' of null
    at atlassian.js:44
    at Object.renderTo (button.js:26)
    at MutationObserver.<anonymous> (button.js:16)

open the issue and hit F12 and check the ouput from console window.
How does your url look like?

**Comment by dorfman2** [comment]
Here's all my errors from the console.

```
DEPRECATED JS - Cookie has been deprecated since 5.8.0 and will be removed in a future release. Use cookie instead.   
 @https://d2st6ip65e1jfi.cloudfront.net/atl-vertigo--shard-jira-prod-us-13--3--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/-egccmf/b/24/84eb17e160bd240d3f8ed3595ae6cb1c/_/download/contextbatch/js/jira.heritage/batch.js?jag=true&locale=en-US:6170:356 batch.js:2964:173
DEPRECATED JS - Cookie has been deprecated since 5.8.0 and will be removed in a future release. Use cookie instead.   
 @https://d2st6ip65e1jfi.cloudfront.net/atl-vertigo--shard-jira-prod-us-13--3--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/-egccmf/b/24/84eb17e160bd240d3f8ed3595ae6cb1c/_/download/contextbatch/js/jira.heritage/batch.js?jag=true&locale=en-US:6674:324 batch.js:2964:173
DEPRECATED JS - Cookie has been deprecated since 5.8.0 and will be removed in a future release. Use cookie instead.   
 @https://d2st6ip65e1jfi.cloudfront.net/atl-vertigo--shard-jira-prod-us-13--3--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/-egccmf/b/24/84eb17e160bd240d3f8ed3595ae6cb1c/_/download/contextbatch/js/jira.heritage/batch.js?jag=true&locale=en-US:6711:408 batch.js:2964:173
DEPRECATED JS - Cookie has been deprecated since 5.8.0 and will be removed in a future release. Use cookie instead.   
 @https://d2st6ip65e1jfi.cloudfront.net/atl-vertigo--shard-jira-prod-us-13--3--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/-egccmf/b/24/84eb17e160bd240d3f8ed3595ae6cb1c/_/download/contextbatch/js/jira.heritage/batch.js?jag=true&locale=en-US:6753:491 batch.js:2964:173
DEPRECATED JS - Cookie has been deprecated since 5.8.0 and will be removed in a future release. Use cookie instead.   
 @https://d2st6ip65e1jfi.cloudfront.net/atl-vertigo--shard-jira-prod-us-13--3--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/-egccmf/b/24/84eb17e160bd240d3f8ed3595ae6cb1c/_/download/contextbatch/js/jira.heritage/batch.js?jag=true&locale=en-US:7105:459 batch.js:2964:173
DEPRECATED JS - Cookie has been deprecated since 5.8.0 and will be removed in a future release. Use cookie instead.   
 @https://d2st6ip65e1jfi.cloudfront.net/atl-vertigo--shard-jira-prod-us-13--3--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/-egccmf/b/24/84eb17e160bd240d3f8ed3595ae6cb1c/_/download/contextbatch/js/jira.heritage/batch.js?jag=true&locale=en-US:7111:178 batch.js:2964:173
WidthDetector will be deprecated, please use WidthObserver from @atlaskit/width-detector instead. async-navigation~atlaskit.2d5302c5db2c6450685d.8.js:1:356563
DEPRECATED JS - Dropdown constructor has been deprecated and will be removed in a future release. Use Dropdown2 instead.   
 @https://d2st6ip65e1jfi.cloudfront.net/atl-vertigo--shard-jira-prod-us-13--3--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/-egccmf/b/24/84eb17e160bd240d3f8ed3595ae6cb1c/_/download/contextbatch/js/jira.heritage/batch.js?jag=true&locale=en-US:6854:201 batch.js:2964:173
WidthDetector will be deprecated, please use WidthObserver from @atlaskit/width-detector instead. async-navigation~atlaskit.2d5302c5db2c6450685d.8.js:1:356563
WidthDetector will be deprecated, please use WidthObserver from @atlaskit/width-detector instead. async-navigation~atlaskit.2d5302c5db2c6450685d.8.js:1:356563
WidthDetector will be deprecated, please use WidthObserver from @atlaskit/width-detector instead. async-navigation~atlaskit.2d5302c5db2c6450685d.8.js:1:356563
WidthDetector will be deprecated, please use WidthObserver from @atlaskit/width-detector instead. async-navigation~atlaskit.2d5302c5db2c6450685d.8.js:1:356563
DEPRECATED JS - Inline dialog constructor has been deprecated and will be removed in a future release. Use inline dialog 2 instead.   
 l@https://d2st6ip65e1jfi.cloudfront.net/atl-vertigo--shard-jira-prod-us-13--3--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/-egccmf/b/24/84eb17e160bd240d3f8ed3595ae6cb1c/_/download/contextbatch/js/jira.heritage/batch.js?jag=true&locale=en-US:6:2054 batch.js:2964:173
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://jira-frontend-static.prod.public.atl-paas.net/assets-brotli/@atlaskit-internal_Dropzone.7967f6ff4cfd822f28f0.8.js
Source Map URL: https://statlas.prod.atl-paas.net/jira-frontend-source-maps/assets/@atlaskit-internal_Dropzone.e4c37204e8d0d2325be7.8.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://jira-frontend-static.prod.public.atl-paas.net/assets-brotli/@atlaskit-internal_media-picker-popup.f1f3abd5662f989df1dc.8.js
Source Map URL: https://statlas.prod.atl-paas.net/jira-frontend-source-maps/assets/@atlaskit-internal_media-picker-popup.e15831198d22ce692cad.8.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://jira-frontend-static.prod.public.atl-paas.net/assets-brotli/@atlaskit-internal_resourcedEmojiComponent.d48601effb3f49a81a28.8.js
Source Map URL: https://statlas.prod.atl-paas.net/jira-frontend-source-maps/assets/@atlaskit-internal_resourcedEmojiComponent.ae28cb4070176babc176.8.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://jira-frontend-static.prod.public.atl-paas.net/assets-brotli/@atlaskit-media-client.555b9f40a8934b558f7c.8.js
Source Map URL: https://statlas.prod.atl-paas.net/jira-frontend-source-maps/assets/@atlaskit-media-client.c58250df6fd61fe57231.8.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://jira-frontend-static.prod.public.atl-paas.net/assets-brotli/@atlaskit-jira_pubsub.191a73207b7e7188dde9.8.js
Source Map URL: https://statlas.prod.atl-paas.net/jira-frontend-source-maps/assets/@atlaskit-jira_pubsub.d9040556fcd4c09fd17c.8.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://jira-frontend-static.prod.public.atl-paas.net/assets-brotli/@atlaskit-internal_MediaCardErrorBoundary.0c79c303db1f64b14af3.8.js
Source Map URL: https://statlas.prod.atl-paas.net/jira-frontend-source-maps/assets/@atlaskit-internal_MediaCardErrorBoundary.7311cc041e8859f365a8.8.js.map
```
