### ISSUE TITLE
Unable to save settings (activate integrations)

### ISSUE THREAD

**Issue by sharky98** [clockify/browser-extension#129]
Hello,

I did a new install on Chrome of the extension (version 1.8.52). I'm using Chrome Version 86.0.4240.111 (Build officiel) (64 bits). I want the integration on GitLab. The button didn't shows up as expected from the instruction. So I checked out the settings. It appears there none integration that are enable by default. I checked the box for Gitlab, didn't saw any button, so expected an auto-save feature in the settings and went again to Gitlab, button still not showing. Went back to settings, Gitlab isn't checked.

So, it seems that I am unable to save settings. In fact, I tried to add custom domain (using the default gitlab.com), the Add button isn't working.

Looking at the console in Chrome I see those errors:
```
settings.html:1 Error handling response: TypeError: Cannot read property 'filter' of undefined
    at chrome-extension://pmjeegjhjdlccodhacdgbgfagbpmccpe/settings.js:166:14
settings.html:1 Error handling response: TypeError: Cannot read property 'filter' of undefined
    at chrome-extension://pmjeegjhjdlccodhacdgbgfagbpmccpe/settings.js:329:14
```

**Comment by sharky98** [comment]
It seems that thoses error have nothing to do with my issue. I used the integrated Chrome Dev Tools to put a breakpoint in the save_permissions() function and the issue seems that `if (result && result.permissions && result.permissions.length > 0)` is always false whenever I check a box.

**Comment by sharky98** [comment]
Today it updated to version 1.8.53 and it now works. Any idea what happens?
