### ISSUE TITLE
extension not adding Play Button on Gitlab issues 

### ISSUE THREAD

**Issue by pealthoff** [clockify/browser-extension#242]
The clockify extension seems to be trying to access the [data-testid="breadcrumb-current-link"] a field before it has been rendered on the page.

Gitlab Version: GitLab Community Edition [15.5.1]
Browser Version:  Chrome 114.0.5735.110 (64-bit) / Firefox 114.0.1 (64-bit) 

``` Uncaught TypeError: Cannot read properties of null (reading 'textContent')
 at gitlab.js:1:842
    at clockifyButton.js:1:1222
    at Array.forEach (<anonymous>)
    at Object.renderTo (clockifyButton.js:1:1164)
    at Object.render (clockifyButton.js:1:1125)
    at gitlab.js:1:489
```

**Comment by 99pswork** [comment]
Hey @pealthoff ,
I tried reproducing this issue multiple times even with slow rendering speeds but this worked smoothly all the times. 
Could you help more in reproducing this issue ?
<img width="954" alt="Screenshot 2023-11-18 at 12 50 58 AM" src="https://github.com/clockify/browser-extension/assets/52522379/2e3ce93a-1d50-49f2-b7e2-fb3507fa382f">

**Comment by pealthoff** [comment]
Hi @99pswork , sorry for the delayed answer, but the problem stopped occurring, I'm not sure if was due to an update. But I've been using it without any problems since then. Thanks!
