### ISSUE TITLE
Atlassian integration not working anymore

### ISSUE THREAD

**Issue by ase-exerp** [clockify/browser-extension#60]
Hi Clockify, 
Seems that the latest update broke the Atlassian integration. Trying to debug myself but got stuck. Integration was working before adding helprace to the mix. Not working on chrome and Firefox. Any idea what the issue could be? 

Thanks

**Comment by ase-exerp** [comment]
here is the Error I get: 

Error handling response: TypeError: Cannot read property 'appendChild' of null
    at file:///Users/adriendesaintseine/Library/Application%20Support/Google/Chrome/Default/Extensions/pmjeegjhjdlccodhacdgbgfagbpmccpe/1.8.8_0/integrations/atlassian.js:31:18
    at Object.renderTo (file:///Users/adriendesaintseine/Library/Application%20Support/Google/Chrome/Default/Extensions/pmjeegjhjdlccodhacdgbgfagbpmccpe/1.8.8_0/integrations/button.js:44:13)
    at file:///Users/adriendesaintseine/Library/Application%20Support/Google/Chrome/Default/Extensions/pmjeegjhjdlccodhacdgbgfagbpmccpe/1.8.8_0/integrations/button.js:38:28
    at file:///Users/adriendesaintseine/Library/Application%20Support/Google/Chrome/Default/Extensions/pmjeegjhjdlccodhacdgbgfagbpmccpe/1.8.8_0/integrations/button.js:16:13
    at file:///Users/adriendesaintseine/Library/Application%20Support/Google/Chrome/Default/Extensions/pmjeegjhjdlccodhacdgbgfagbpmccpe/1.8.8_0/integrations/button.js:147:9

**Comment by ase-exerp** [comment]
Figured out that I am using the Old view. In this case the integration is not working and I am get the exception above. 

Integration is working fine using the New view.

**Comment by andrewnicols** [comment]
Also trying this extension out with a view to purchasing the software, and it does not work either with our Jira instance (7.12) or even jira.atlassian.org.

Additionally this repo has a much older version of the code than is available in the Chrome store.
